export interface Template {
  id: string;
  slug: string;
  name: string;
  category: 'SaaS' | 'Agency' | 'Local' | 'Creative' | 'Coach' | 'Professional' | 'Education';
  price: number;
  description: string;
  longDescription: string;
  image: string;
  featured?: boolean;
  demoUrl: string;
  pages: string[];
  features: string[];
  techStack: string[];
}

export const templates: Template[] = [
  {
    id: 'minimal-starter',
    slug: 'minimal-starter',
    name: 'Minimal Starter',
    category: 'SaaS',
    price: 99,
    description: 'Clean, modern SaaS landing with GSAP animations',
    longDescription: 'A beautifully minimal SaaS landing page that focuses on clarity and conversion. Features smooth GSAP scroll animations, a clean hero section, and optimized for fast load times.',
    image: '/templates/minimal-starter.png',
    featured: true,
    demoUrl: 'https://minimal-starter.vercel.app',
    pages: ['Home', 'Features', 'Pricing', 'Contact'],
    features: ['GSAP scroll animations', 'Responsive hero section', 'Feature grid', 'Pricing table', 'Contact form', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'GSAP', 'Sanity CMS'],
  },
  {
    id: 'aurora-starter',
    slug: 'aurora-starter',
    name: 'Aurora Starter',
    category: 'SaaS',
    price: 99,
    description: 'Glassmorphism SaaS with smooth transitions',
    longDescription: 'Stunning glassmorphism design with aurora-inspired gradients and buttery smooth transitions. Perfect for modern SaaS products that want to stand out.',
    image: '/templates/aurora-starter.png',
    featured: true,
    demoUrl: 'https://aurora-starter.vercel.app',
    pages: ['Home', 'Features', 'Pricing', 'About', 'Contact'],
    features: ['Glassmorphism design', 'Aurora gradients', 'Framer Motion animations', 'Interactive pricing', 'Newsletter signup', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity CMS'],
  },
  {
    id: 'saas-pro',
    slug: 'saas-pro',
    name: 'SaaS Pro',
    category: 'SaaS',
    price: 99,
    description: 'Full SaaS marketing site with pricing & blog',
    longDescription: 'The most comprehensive SaaS template in the bundle. Includes everything you need: marketing pages, blog with MDX support, pricing with toggle, testimonials, and more.',
    image: '/templates/saas-pro.png',
    featured: true,
    demoUrl: 'https://saas-pro.vercel.app',
    pages: ['Home', 'Features', 'Pricing', 'Blog', 'Blog Post', 'About', 'Contact', 'Terms', 'Privacy'],
    features: ['Complete marketing site', 'Blog with MDX', 'Pricing toggle', 'Testimonial carousel', 'FAQ accordion', 'Newsletter integration', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'MDX', 'Sanity CMS'],
  },
  {
    id: 'agency-starter',
    slug: 'agency-starter',
    name: 'Agency Starter',
    category: 'Agency',
    price: 99,
    description: 'Bold agency portfolio with case studies',
    longDescription: 'A bold and confident agency template designed to showcase your best work. Features dynamic case study pages, team section, and impressive scroll animations.',
    image: '/templates/agency-starter.png',
    featured: true,
    demoUrl: 'https://agency-starter.vercel.app',
    pages: ['Home', 'Work', 'Case Study', 'About', 'Team', 'Contact'],
    features: ['Case study showcase', 'Project grid', 'Team profiles', 'Client logos', 'Scroll animations', 'Contact form', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'GSAP', 'Sanity CMS'],
  },
  {
    id: 'studio-starter',
    slug: 'studio-starter',
    name: 'Studio Starter',
    category: 'Agency',
    price: 99,
    description: 'Refined design studio with project showcase',
    longDescription: 'An elegant and refined template for design studios and creative agencies. Minimalist approach with sophisticated typography and smooth reveal animations.',
    image: '/templates/studio-starter.png',
    demoUrl: 'https://studio-starter.vercel.app',
    pages: ['Home', 'Projects', 'Project Detail', 'Studio', 'Contact'],
    features: ['Project showcase', 'Minimal design', 'Typography focus', 'Image galleries', 'Reveal animations', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity CMS'],
  },
  {
    id: 'typography-starter',
    slug: 'typography-starter',
    name: 'Typography Starter',
    category: 'Creative',
    price: 99,
    description: 'Typography-focused creative portfolio',
    longDescription: 'For designers and creatives who appreciate the art of typography. Large, bold text treatments with creative layouts and smooth text animations.',
    image: '/templates/typography-starter.png',
    demoUrl: 'https://typography-starter.vercel.app',
    pages: ['Home', 'Work', 'About', 'Contact'],
    features: ['Typography-first design', 'Creative layouts', 'Text animations', 'Portfolio grid', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'GSAP', 'SplitType', 'Sanity CMS'],
  },
  {
    id: 'brutalist-starter',
    slug: 'brutalist-starter',
    name: 'Brutalist Starter',
    category: 'Creative',
    price: 99,
    description: 'Edgy brutalist design with raw aesthetics',
    longDescription: 'Break the mold with this edgy brutalist template. Raw, unpolished aesthetics that make a bold statement. Perfect for experimental brands and artists.',
    image: '/templates/brutalist-starter.png',
    demoUrl: 'https://brutalist-starter.vercel.app',
    pages: ['Home', 'Projects', 'Manifesto', 'Contact'],
    features: ['Brutalist aesthetics', 'Bold typography', 'Raw design elements', 'Unconventional layouts', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity CMS'],
  },
  {
    id: 'restaurant-starter',
    slug: 'restaurant-starter',
    name: 'Restaurant Starter',
    category: 'Local',
    price: 99,
    description: 'Elegant restaurant with menu & reservations',
    longDescription: 'An elegant and appetizing template for restaurants and fine dining establishments. Features beautiful menu displays, reservation system integration, and gallery.',
    image: '/templates/restaurant-starter.png',
    demoUrl: 'https://ck-restaurant-starter.vercel.app/',
    pages: ['Home', 'Menu', 'About', 'Gallery', 'Reservations', 'Contact'],
    features: ['Menu display', 'Reservation form', 'Photo gallery', 'Hours & location', 'Chef profiles', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity CMS'],
  },
  {
    id: 'brunch-starter',
    slug: 'brunch-starter',
    name: 'Brunch Starter',
    category: 'Local',
    price: 99,
    description: 'Warm cafe/brunch spot template',
    longDescription: 'A warm and inviting template perfect for cafes, brunch spots, and coffee shops. Cozy vibes with beautiful food photography layouts and simple menu display.',
    image: '/templates/brunch-starter.png',
    demoUrl: 'https://brunch-starter.vercel.app',
    pages: ['Home', 'Menu', 'About', 'Contact'],
    features: ['Cozy design', 'Menu sections', 'Instagram feed', 'Location map', 'Hours display', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity CMS'],
  },
  {
    id: 'salon-starter',
    slug: 'salon-starter',
    name: 'Salon Starter',
    category: 'Local',
    price: 99,
    description: 'Luxurious salon/spa with booking',
    longDescription: 'A luxurious and relaxing template for salons, spas, and beauty businesses. Features elegant service displays, staff profiles, and online booking integration.',
    image: '/templates/salon-starter.png',
    demoUrl: 'https://templates-xi-eight.vercel.app/',
    pages: ['Home', 'Services', 'Team', 'Gallery', 'Book Now', 'Contact'],
    features: ['Service menu', 'Online booking', 'Staff profiles', 'Before/after gallery', 'Testimonials', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity CMS'],
  },
  {
    id: 'gym-starter',
    slug: 'gym-starter',
    name: 'Gym Starter',
    category: 'Local',
    price: 99,
    description: 'Energetic fitness center template',
    longDescription: 'An energetic and motivating template for gyms, fitness centers, and personal trainers. Bold design with class schedules, membership tiers, and trainer profiles.',
    image: '/templates/gym-starter.png',
    demoUrl: 'https://gym-starter.vercel.app',
    pages: ['Home', 'Classes', 'Trainers', 'Membership', 'Contact'],
    features: ['Class schedule', 'Trainer profiles', 'Membership pricing', 'Facility gallery', 'Trial signup', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity CMS'],
  },
  {
    id: 'contractor-starter',
    slug: 'contractor-starter',
    name: 'Contractor Starter',
    category: 'Local',
    price: 99,
    description: 'Trustworthy home services contractor',
    longDescription: 'A professional and trustworthy template for contractors, plumbers, electricians, and home service businesses. Builds trust with testimonials, certifications, and project galleries.',
    image: '/templates/contractor-starter.png',
    demoUrl: 'https://contractor-starter.vercel.app',
    pages: ['Home', 'Services', 'Projects', 'About', 'Contact', 'Quote'],
    features: ['Service list', 'Project gallery', 'Trust badges', 'Testimonials', 'Quote request form', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity CMS'],
  },
  {
    id: 'coach-starter',
    slug: 'coach-starter',
    name: 'Coach Starter',
    category: 'Coach',
    price: 99,
    description: 'Personal coach/consultant with booking',
    longDescription: 'A personal and inspiring template for coaches, consultants, and mentors. Features about story, service packages, testimonials, and integrated booking.',
    image: '/templates/coach-starter.png',
    demoUrl: 'https://ck-coach-starter.vercel.app/',
    pages: ['Home', 'About', 'Services', 'Testimonials', 'Blog', 'Book a Call', 'Contact'],
    features: ['Personal branding', 'Service packages', 'Testimonial showcase', 'Blog section', 'Booking integration', 'Newsletter signup', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Cal.com', 'Sanity CMS'],
  },
  {
    id: 'realestate-starter',
    slug: 'realestate-starter',
    name: 'Real Estate Starter',
    category: 'Professional',
    price: 99,
    description: 'Luxury real estate agency with listings',
    longDescription: 'A premium real estate template for agencies and brokers. Features property listings with filters, agent profiles, neighborhood guides, and contact forms.',
    image: '/templates/realestate-starter.png',
    demoUrl: 'https://ck-realestate-starter.vercel.app/',
    pages: ['Home', 'Listings', 'Listing Detail', 'Agents', 'Agent Detail', 'About', 'Contact'],
    features: ['Property listings', 'Search & filters', 'Agent profiles', 'Image galleries', 'Neighborhood guides', 'Contact forms', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity CMS'],
  },
  {
    id: 'lawfirm-starter',
    slug: 'lawfirm-starter',
    name: 'Law Firm Starter',
    category: 'Professional',
    price: 99,
    description: 'Professional law firm with practice areas',
    longDescription: 'A trustworthy and authoritative template for law firms and legal services. Features practice areas, attorney profiles, case results, and consultation booking.',
    image: '/templates/lawfirm-starter.png',
    demoUrl: 'https://lawfirm-starter.vercel.app',
    pages: ['Home', 'Practice Areas', 'Practice Area Detail', 'Attorneys', 'Attorney Detail', 'About', 'Results', 'Contact'],
    features: ['Practice areas', 'Attorney profiles', 'Case results', 'Legal disclaimers', 'Consultation forms', 'Trust badges', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity CMS'],
  },
  {
    id: 'course-starter',
    slug: 'course-starter',
    name: 'Course Starter',
    category: 'Education',
    price: 99,
    description: 'Online course platform with curriculum',
    longDescription: 'A conversion-focused template for course creators and educators. Features curriculum breakdown, pricing tiers, student testimonials, and enrollment CTAs.',
    image: '/templates/course-starter.png',
    demoUrl: 'https://course-starter.vercel.app',
    pages: ['Home', 'Curriculum', 'About', 'Testimonials', 'Pricing', 'FAQ', 'Contact'],
    features: ['Curriculum modules', 'Pricing tiers', 'Video testimonials', 'Instructor profile', 'FAQ accordion', 'Newsletter signup', 'Light mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity CMS'],
  },
  {
    id: 'photographer-starter',
    slug: 'photographer-starter',
    name: 'Photographer Starter',
    category: 'Creative',
    price: 99,
    description: 'Visual portfolio for photographers',
    longDescription: 'An elegant, visual-first portfolio template for photographers and visual artists. Features masonry galleries, lightbox viewer, service packages, and booking.',
    image: '/templates/photographer-starter.png',
    demoUrl: 'https://photographer-starter.vercel.app',
    pages: ['Home', 'Portfolio', 'Project Detail', 'About', 'Services', 'Contact'],
    features: ['Masonry gallery', 'Lightbox viewer', 'Category filters', 'Service packages', 'Contact form', 'Social links', 'Dark mode'],
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity CMS'],
  },
];

export const categories = ['All', 'SaaS', 'Agency', 'Local', 'Creative', 'Coach', 'Professional', 'Education'] as const;
export type Category = (typeof categories)[number];

export function getTemplateBySlug(slug: string): Template | undefined {
  return templates.find((t) => t.slug === slug);
}

export function getRelatedTemplates(template: Template, limit = 4): Template[] {
  return templates
    .filter((t) => t.id !== template.id && t.category === template.category)
    .slice(0, limit)
    .concat(
      templates
        .filter((t) => t.id !== template.id && t.category !== template.category)
        .slice(0, limit)
    )
    .slice(0, limit);
}
